package model;
// Generated 11-ago-2016 12:41:23 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Almacen generated by hbm2java
 */
@Entity
@Table(name="almacen"
    ,catalog="camiones"
)
public class Almacen  implements java.io.Serializable {


     private int numeroAlmacen;
     private String direccionAlmacen;
     private Long telefonoAlmacen;
     private Set pedidos = new HashSet(0);
     private Set tiendas = new HashSet(0);

    public Almacen() {
    }

	
    public Almacen(int numeroAlmacen) {
        this.numeroAlmacen = numeroAlmacen;
    }
    public Almacen(int numeroAlmacen, String direccionAlmacen, Long telefonoAlmacen, Set pedidos, Set tiendas) {
       this.numeroAlmacen = numeroAlmacen;
       this.direccionAlmacen = direccionAlmacen;
       this.telefonoAlmacen = telefonoAlmacen;
       this.pedidos = pedidos;
       this.tiendas = tiendas;
    }
   
     @Id 

    
    @Column(name="NUMERO_ALMACEN", unique=true, nullable=false)
    public int getNumeroAlmacen() {
        return this.numeroAlmacen;
    }
    
    public void setNumeroAlmacen(int numeroAlmacen) {
        this.numeroAlmacen = numeroAlmacen;
    }

    
    @Column(name="DIRECCION_ALMACEN", length=100)
    public String getDireccionAlmacen() {
        return this.direccionAlmacen;
    }
    
    public void setDireccionAlmacen(String direccionAlmacen) {
        this.direccionAlmacen = direccionAlmacen;
    }

    
    @Column(name="TELEFONO_ALMACEN", precision=15, scale=0)
    public Long getTelefonoAlmacen() {
        return this.telefonoAlmacen;
    }
    
    public void setTelefonoAlmacen(Long telefonoAlmacen) {
        this.telefonoAlmacen = telefonoAlmacen;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="almacen")
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="almacen")
    public Set getTiendas() {
        return this.tiendas;
    }
    
    public void setTiendas(Set tiendas) {
        this.tiendas = tiendas;
    }




}


