package model;
// Generated 11-ago-2016 12:41:23 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Camion generated by hbm2java
 */
@Entity
@Table(name="camion"
    ,catalog="camiones"
)
public class Camion  implements java.io.Serializable {


     private int matriculaCamion;
     private CompaniaCamion companiaCamion;
     private BigDecimal limitemaxCamion;
     private Integer numeroEntregaSemCamiones;
     private Set viajes = new HashSet(0);

    public Camion() {
    }

	
    public Camion(int matriculaCamion, CompaniaCamion companiaCamion) {
        this.matriculaCamion = matriculaCamion;
        this.companiaCamion = companiaCamion;
    }
    public Camion(int matriculaCamion, CompaniaCamion companiaCamion, BigDecimal limitemaxCamion, Integer numeroEntregaSemCamiones, Set viajes) {
       this.matriculaCamion = matriculaCamion;
       this.companiaCamion = companiaCamion;
       this.limitemaxCamion = limitemaxCamion;
       this.numeroEntregaSemCamiones = numeroEntregaSemCamiones;
       this.viajes = viajes;
    }
   
     @Id 

    
    @Column(name="MATRICULA_CAMION", unique=true, nullable=false)
    public int getMatriculaCamion() {
        return this.matriculaCamion;
    }
    
    public void setMatriculaCamion(int matriculaCamion) {
        this.matriculaCamion = matriculaCamion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COMPANIA", nullable=false)
    public CompaniaCamion getCompaniaCamion() {
        return this.companiaCamion;
    }
    
    public void setCompaniaCamion(CompaniaCamion companiaCamion) {
        this.companiaCamion = companiaCamion;
    }

    
    @Column(name="LIMITEMAX_CAMION", precision=5)
    public BigDecimal getLimitemaxCamion() {
        return this.limitemaxCamion;
    }
    
    public void setLimitemaxCamion(BigDecimal limitemaxCamion) {
        this.limitemaxCamion = limitemaxCamion;
    }

    
    @Column(name="NUMERO_ENTREGA_SEM_CAMIONES")
    public Integer getNumeroEntregaSemCamiones() {
        return this.numeroEntregaSemCamiones;
    }
    
    public void setNumeroEntregaSemCamiones(Integer numeroEntregaSemCamiones) {
        this.numeroEntregaSemCamiones = numeroEntregaSemCamiones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camion")
    public Set getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set viajes) {
        this.viajes = viajes;
    }




}


