package model;
// Generated 11-ago-2016 12:41:23 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="camiones"
)
public class Producto  implements java.io.Serializable {


     private String idProducto;
     private String descripcionProducto;
     private BigDecimal pesoProducto;
     private BigDecimal precioProducto;
     private Set pedidos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String idProducto) {
        this.idProducto = idProducto;
    }
    public Producto(String idProducto, String descripcionProducto, BigDecimal pesoProducto, BigDecimal precioProducto, Set pedidos) {
       this.idProducto = idProducto;
       this.descripcionProducto = descripcionProducto;
       this.pesoProducto = pesoProducto;
       this.precioProducto = precioProducto;
       this.pedidos = pedidos;
    }
   
     @Id 

    
    @Column(name="ID_PRODUCTO", unique=true, nullable=false, length=10)
    public String getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(String idProducto) {
        this.idProducto = idProducto;
    }

    
    @Column(name="DESCRIPCION_PRODUCTO", length=100)
    public String getDescripcionProducto() {
        return this.descripcionProducto;
    }
    
    public void setDescripcionProducto(String descripcionProducto) {
        this.descripcionProducto = descripcionProducto;
    }

    
    @Column(name="PESO_PRODUCTO", precision=3)
    public BigDecimal getPesoProducto() {
        return this.pesoProducto;
    }
    
    public void setPesoProducto(BigDecimal pesoProducto) {
        this.pesoProducto = pesoProducto;
    }

    
    @Column(name="PRECIO_PRODUCTO", precision=4)
    public BigDecimal getPrecioProducto() {
        return this.precioProducto;
    }
    
    public void setPrecioProducto(BigDecimal precioProducto) {
        this.precioProducto = precioProducto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


