package model;
// Generated 11-ago-2016 12:41:23 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "camiones"
)
public class Usuario implements java.io.Serializable {

    private int idUsuario=0;
    private String rolId;
    private String usuario;
    private String password;
    private String emailUsuario;
    private Date fechaCreacionUsuario;
    private Date fechaClaveUsuario;
    private boolean estadoUsuario;

    public Usuario() {
        this.idUsuario = 0;
    }

    public Usuario(int idUsuario, String rolId, String usuario, String password, String emailUsuario, Date fechaCreacionUsuario, Date fechaClaveUsuario, boolean estadoUsuario) {
        this.idUsuario = idUsuario;
        this.rolId = rolId;
        this.usuario = usuario;
        this.password = password;
        this.emailUsuario = emailUsuario;
        this.fechaCreacionUsuario = fechaCreacionUsuario;
        this.fechaClaveUsuario = fechaClaveUsuario;
        this.estadoUsuario = estadoUsuario;
    }

    @Id

    @Column(name = "id_usuario", unique = true, nullable = false)
    public int getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Column(name = "rol_id", nullable = false, length = 10)
    public String getRolId() {
        return this.rolId;
    }

    public void setRolId(String rolId) {
        this.rolId = rolId;
    }

    @Column(name = "usuario", nullable = false, length = 25)
    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    @Column(name = "password", nullable = false, length = 25)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "email_usuario", nullable = false, length = 30)
    public String getEmailUsuario() {
        return this.emailUsuario;
    }

    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_creacion_usuario", nullable = false, length = 10)
    public Date getFechaCreacionUsuario() {
        return this.fechaCreacionUsuario;
    }

    public void setFechaCreacionUsuario(Date fechaCreacionUsuario) {
        this.fechaCreacionUsuario = fechaCreacionUsuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_clave_usuario", nullable = false, length = 10)
    public Date getFechaClaveUsuario() {
        return this.fechaClaveUsuario;
    }

    public void setFechaClaveUsuario(Date fechaClaveUsuario) {
        this.fechaClaveUsuario = fechaClaveUsuario;
    }

    @Column(name = "estado_usuario", nullable = false)
    public boolean isEstadoUsuario() {
        return this.estadoUsuario;
    }

    public void setEstadoUsuario(boolean estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }

}
