package model;
// Generated 11-ago-2016 12:41:23 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Viaje generated by hbm2java
 */
@Entity
@Table(name="viaje"
    ,catalog="camiones"
)
public class Viaje  implements java.io.Serializable {


     private int numeroViaje;
     private Camion camion;
     private Date fechaViaje;
     private BigDecimal pesotransportadoViaje;
     private Set pedidos = new HashSet(0);

    public Viaje() {
    }

	
    public Viaje(int numeroViaje, Camion camion) {
        this.numeroViaje = numeroViaje;
        this.camion = camion;
    }
    public Viaje(int numeroViaje, Camion camion, Date fechaViaje, BigDecimal pesotransportadoViaje, Set pedidos) {
       this.numeroViaje = numeroViaje;
       this.camion = camion;
       this.fechaViaje = fechaViaje;
       this.pesotransportadoViaje = pesotransportadoViaje;
       this.pedidos = pedidos;
    }
   
     @Id 

    
    @Column(name="NUMERO_VIAJE", unique=true, nullable=false)
    public int getNumeroViaje() {
        return this.numeroViaje;
    }
    
    public void setNumeroViaje(int numeroViaje) {
        this.numeroViaje = numeroViaje;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MATRICULA_CAMION", nullable=false)
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_VIAJE", length=10)
    public Date getFechaViaje() {
        return this.fechaViaje;
    }
    
    public void setFechaViaje(Date fechaViaje) {
        this.fechaViaje = fechaViaje;
    }

    
    @Column(name="PESOTRANSPORTADO_VIAJE", precision=5)
    public BigDecimal getPesotransportadoViaje() {
        return this.pesotransportadoViaje;
    }
    
    public void setPesotransportadoViaje(BigDecimal pesotransportadoViaje) {
        this.pesotransportadoViaje = pesotransportadoViaje;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="viaje")
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


